language: java
sudo: enabled
services:
  - mysql
  
before_install:
    sudo mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
    udo mysql -e 'CREATE DATABASE IF NOT EXISTS pruebas_db;'
    sudo mysql -e 'USE pruebas_db;
              CREATE TABLE IF NOT EXISTS alumnos_tbl(
              id varchar(10) not null,
              nombre varchar(50) not null,
              email varchar(100) not null,
              edad int not null,
              constraint alumnos_tbl_pk
              primary key (ID)
              );'
