  language:
      - java
  services:
      - mysql
      - xvfb
  jdk:
      - oraclejdk8
      - openjdk7
  before_install:
      - mysql -u root < travis.sql
  script:
      - mvn clean test
      - xvfb-run make test
      - xvfb-run --server-args="-screen 0 1024x768x24" make test
  cache:
      directories:
          - $HOME/.m2
  dist:
      - trusty
      - xenial
  sudo:
      - false
  notifications:
      - email: false
