language: java
sudo: enabled
services:
  - mysql
  
before_install:
    sudo mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
    udo mysql -e 'CREATE DATABASE IF NOT EXISTS pruebas_db;'
    sudo mysql -e 'USE pruebas_db;
